const recipes = [
  {
    title: 'קינואה יאמי',
    description: 'הקינואה הכי טובה שתאכלו, יותר טובה משל סבתא',
    author: 'יוסי מולה',
    category: 'מאכלים',
    ingredients: [
      { name: 'בצל', ammount: 1 },
      { name: 'שן שום', ammount: 1 },
      { name: 'קינואה', ammount: 200 },
      { name: 'כף שמן זית', ammount: 1 },
      { name: 'כפית מלח', ammount: 0.5 },
    ],
    website: 'www.google.com',
    instructions: [
      'שוטפים חלילה את הקינואה עד שמתקבלים מים צלולים',
      'מטגנים בסיר עם שמן למשך 2 דקות',
      'מוסיפים 2 כוסות מים רותחים לסיר',
      'מכסים את הסיר ומורידים לאש נמוכה כ-15דק עד התרככות הקינואה',
      'מכבים את האש ומחכים כ-5דקות',
    ],
    images: [
      'https://imaot.co.il/images/Uploads/RecipeImages/5524492022019.jpg',
    ],
    prepTime: 15,
    cookingTime: 20,
    difficulty: 'קל',
    tags: ['פצצת חלבון', 'קל להכנה'],
    remarks: 'שימו לב לא לפתוח את הסיר בזמן הבישול',
    comments: [],
    rating: 0,
    dishesAmmount: 2,
    createdBy: '',
  },

  {
    title: 'קורנפלקס של חתיכים',
    description: 'עזבו אליפויות, יופי זה הדיבור היום',
    author: 'אלי אברהמי',
    category: 'מאכלים',
    website: 'www.google.com',
    ingredients: [
      { name: 'כפית מלח', ammount: 0.5 },
      { name: 'כפית סוכר', ammount: 2 },
      { name: 'גרם קורנפלקס', ammount: 100 },
      { name: 'מ"ל חלב', ammount: 400 },
    ],
    instructions: [
      'להוציא חלב מהמקרר',
      'לשקשק את החלב',
      'למזוג את כמות הקורנפלקס הרצויה לקערה',
      'למזוג את כמות החלב הרצוויה לקערה',
      'לאכול בתיאבון',
    ],
    images: [
      'https://www.kosher.com/resized/article_view/s/h/shutterstock_1021375678banner.jpg',
    ],
    prepTime: 1,
    cookingTime: 3,
    difficulty: 'קל',
    tags: ['קל להכנה', 'מעולה לעצלנים'],
    remarks: 'אחלה מנה. אפשרי עם קורנפלקס של אלופים או קורנפלקס של חתיכים',
    comments: [
      { name: 'משה מנחם', comment: 'אחד המתכונים. החלב בכלל עושה את המתכון' },
      {
        name: 'יוסף ביטון',
        comment: 'אני אישית מעדיף חלב עיזים. אבל תודה על המתכון!',
      },
      {
        name: 'יוסף ביטון',
        comment: 'אני אישית מעדיף חלב עיזים. אבל תודה על המתכון!',
      },
    ],
    rating: 0,
    dishesAmmount: 5,
    createdBy: '',
  },

  {
    title: 'פאי בשר טבעוני',
    description: 'פאי עם בשר, רק שהבשר הוא לא באמת בשר',
    author: 'דוד אורן',
    category: 'מאכלים',
    ingredients: [
      { name: 'בצל גדול קצוץ דק', ammount: 1 },
      { name: 'גרם טופו קשה חתוך בינוני', ammount: 300 },
      { name: 'שיני שום כתושות', ammount: 2 },
      { name: 'גזר חתוך לקוביות קטנות מבושל', ammount: 1 },
      { name: 'גרם אפונה מוכנה לאכילה', ammount: 300 },
    ],
    instructions: [
      'על מחבת רחבה ועמוקה לטגן בצל עד שזהוב כהה',
      'להוסיף חתיכות טופו ולטגן יחד 3-4 דקות',
      'להוסיף שום ולטגן 1-2 דקות',
      'להוסיף אפונה וגזר ולערבב',
      'להוסיף רוטב סויה, בלסמי ורסק עגבניות ולבשל 1-2 דקות',
      'להוסיף תבלינים ולערבב טוב',
      'להוסיף יין / מים ולבשל תוך כדי ערבוב 3-4 דקות עד שסמיך וארומתי',
    ],
    images: [
      'https://tivoneat.co.il/wp-content/uploads/2020/11/%D7%A4%D7%90%D7%99-%D7%91%D7%A8%D7%99%D7%98%D7%990-copy.jpg',
    ],
    prepTime: 25,
    cookingTime: 20,
    difficulty: 'קשה',
    tags: ['טעים ומשביע', 'מתכון מתקדם'],
    remarks: 'הבצל צריך להיוות ענק',
    comments: [
      { name: 'פרה', comment: 'וואללה היה טעים. יותר מחברות שלי בחווה' },
      { name: 'אסף', comment: 'נחמד ביותר. המרקם נעים אבל המתכון לא מדוייק' },
      {
        name: 'יוסף ביטון',
        comment: 'אני אישית מעדיף חלב עיזים. אבל תודה על המתכון!',
      },
    ],
    rating: 0,
    dishesAmmount: 3,
    createdBy: '',
  },
  {
    description: "איזו מילה מגניבה זו מג'דרה, תודו",
    title: 'מג׳דרה עדשים שחורות',
    author: 'דוד אורן',
    category: 'מאכלים',
    website: 'www.google.com',

    ingredients: [
      { name: 'כוס אורז בסמטי קלאסי', ammount: 1.25 },
      { name: 'בצל גדול חתוך לרצועות דקות', ammount: 1 },
      { name: 'כפיות כמון', ammount: 1.5 },
      { name: 'כף שום גבישי', ammount: 1 },
      { name: 'מלח על פי הטעם' },
      { name: 'שמן זית לטיגון' },
    ],
    instructions: [
      'בסיר עמוק לחמם כמה כפות שמן זית (או רגיל)',
      'לטגן את הבצל לפחות 5 דקות עד שהוא ממש קריספי',
      'להפריד חצי מכמות הבצל המטוגן לקערית ולהניח בצד',
      'להוסיף לסיר (על הבצל שהשארנו שם) את האורז ולערבב טוב',
      'להוסיף 2 כוסות מים, כמון, שום ומלח ולערבב',
      'לכסות ולבשל 10 דקות או עד שהאורז מוכן',
      'להשאיר מכוסה עד שהעדשים מוכנות',
    ],
    images: [
      'https://images1.ynet.co.il/xnet//PicServer2/pic/102015/659452/1_7.jpg',
    ],
    prepTime: 10,
    cookingTime: 30,
    difficulty: 'בינוני',
    tags: ['טעים ומשביע', 'פצצת חלבון'],
    remarks: "מג'דרה זו מילה מגניבה רצח",
    comments: [],
    rating: 0,
    dishesAmmount: 2,
    createdBy: '',
  },
];

module.exports = recipes;
